### ISSUE TITLE
add daily checklist functionality

### ISSUE THREAD

**Issue by silbinarywolf** [silbinarywolf/desk-breaker#10]
**The problem**

Every day there are certain exercises I should be doing to help with my RSI. I want to code up an options screen where I can define a bunch of items that should be done over the course of a day and anytime an "activity break" screen comes on, I can see what needs doing and check that item off.

ie. **Daily Checklist**
- [ ] Do Tennis ball rolls on arm
- [ ] Lay on rolled up towel for 5 minutes
- [ ] Do 15 minutes of Ring Fit exercises

I'd ideally like this data to be stored by year/month/day too so that the application can read this data and give you feedback on what you actually achieved that week.
`userdata/daily/2024/09/15.json`
